#!/usr/bin/env node
// scripts/vna/door-labels.mjs — C243 ONE NAME FOR THE KEYS DOOR, WITH THE KEY (operator 2026-09-24, verbatim, on a screenshot of
// the page header "⚙️ Engine & Keys": "engine & keys - and key emoji").
//
// The sidebar pill (steer-ui.mjs, node) and the page (vna-engines.ts, the extension host) are ONE door; they read ONE label from
// here. The extension cannot import a repo .mjs (tsconfig rootDir is src/, and the vsix packs no scripts/), so the TS side reads a
// GENERATED mirror, packages/thetacog-mcp-vscode/src/door-labels.ts — the same pattern as receipt-globs.mjs (C109l): this file is
// the source, the mirror is derived, and tests/vna/c243-one-name-for-the-keys-door.test.mjs diffs the committed mirror against
// `--print`, so a label changed here and not regenerated is a red test, never two names on two surfaces.
//   node scripts/vna/door-labels.mjs            regenerate the TS mirror
//   node scripts/vna/door-labels.mjs --print    print it, write nothing
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/** the one label of the keys door — the pill, the panel title, the h1, the status-bar tooltip */
export const ENGINE_KEYS_LABEL = '⚙️🔑 Engine & Keys';
/** the same label for an HTML text node (the h1) — derived, never a second literal */
export const ENGINE_KEYS_LABEL_HTML = ENGINE_KEYS_LABEL.replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
/** the one command that opens it (C179: one door, never a second) */
export const ENGINE_KEYS_COMMAND = 'vna.openEnginesConfig';

const REPO = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
export const OUT = resolve(REPO, 'packages/thetacog-mcp-vscode/src/door-labels.ts');

export function render() {
  return `// GENERATED by scripts/vna/door-labels.mjs — never edit by hand (C243). One name for the keys door: the pill (steer-ui.mjs)
// and this page (vna-engines.ts) both read it; the guard diffs this file against the generator's --print.
export const ENGINE_KEYS_LABEL = ${JSON.stringify(ENGINE_KEYS_LABEL)};
export const ENGINE_KEYS_LABEL_HTML = ${JSON.stringify(ENGINE_KEYS_LABEL_HTML)};
export const ENGINE_KEYS_COMMAND = ${JSON.stringify(ENGINE_KEYS_COMMAND)};
`;
}

// Any way of naming the door in text: "Engine & Keys" / "Engine &amp; Keys" / "Engine keys" / "Engines & Keys" / the C166-era
// "Engines, Keys & Licences". The CONSTRUCT is "a code line that names the door"; a comment line is not a surface.
const DOOR_NAME_RE = /\bEngines?(?:,\s*Keys\s*(?:&amp;|&)\s*Licences|\s*(?:&amp;|&|and)?\s+Keys)\b/gi;   // a space before Keys: prose, never the identifier engineKeys
const stripBlockComments = (s) => s.replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '));
/**
 * The code lines of `source` that carry a re-typed door name.
 *   mode 'any'       — every literal is a re-type (the surface must import the constant): steer-ui.mjs, vna-engines.ts
 *   mode 'divergent' — only a name that is not exactly ENGINE_KEYS_LABEL (or its html form): a webview script, package.json, README
 * A line whose first non-space characters are `//`, `#`, `*` or `<!--` is a comment and is never a surface.
 */
export function retypedDoorNames(source, { mode = 'any' } = {}) {
  const out = [];
  stripBlockComments(String(source)).split('\n').forEach((raw, i) => {
    if (/^\s*(\/\/|#|\*|<!--)/.test(raw)) return;
    const hits = raw.match(DOOR_NAME_RE) || [];
    for (const hit of hits) {
      const at = raw.indexOf(hit);
      // the full token as written: walk back over the emoji cluster that may precede the name (⚙️🔑 …)
      const before = raw.slice(0, at).match(/(?:[☀-➿️]|[\uD83C-\uDBFF][\uDC00-\uDFFF])+\s*$/);
      const written = (before ? before[0] : '') + hit;
      const exact = written === ENGINE_KEYS_LABEL || written === ENGINE_KEYS_LABEL_HTML;
      if (mode === 'divergent' && exact) continue;
      out.push({ line: i + 1, written: written.trim() });
    }
  });
  return out;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = render();
  if (process.argv.includes('--print')) process.stdout.write(text);
  else { writeFileSync(OUT, text); console.log(`door-labels: ${ENGINE_KEYS_LABEL} → ${OUT.slice(REPO.length + 1)}`); }
}
