#!/usr/bin/env node
// scripts/pmu/prereg-seal.mjs
//
// Seal a pre-registration manifest into a bearer hypothesis token.
//
// THE POINT (operator, 2026-06-16): "Once sealed, the results are a measurement
// of physics, not a negotiation." A pre-registration only has teeth if the
// hypothesis bytes are FROZEN before the held-out is opened. This script:
//
//   1. Takes the FROZEN BODY of the manifest = everything ABOVE the sentinel
//      line `<!-- PREREG-SEAL-BELOW -->`. Nothing below the sentinel is hashed,
//      so injecting the seal block back into the file does NOT change the body
//      that was signed (re-runnable, idempotent, self-verifying).
//   2. Pins the two artifacts the hypothesis is ABOUT — the reef (lens lexicon)
//      and the deployed seed-library (the lens itself) — by sha256. If either
//      changes, the seal no longer matches and the pre-registration is void.
//   3. ed25519-signs the whole thing with the host key (receipt-crypto.mjs), so
//      the seal is a bearer token: anyone holding the file + sidecar can verify
//      it was frozen by this host at seal time, with no trusted third party.
//
// Usage:
//   node scripts/pmu/prereg-seal.mjs docs/research/pmu-shape-detection-prereg.md
//   node scripts/pmu/prereg-seal.mjs <manifest.md> --verify   # check, don't reseal
//   node scripts/pmu/prereg-seal.mjs <manifest.md> --json     # machine output

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname, basename, join } from 'node:path';
import { sealReceipt, verifyReceipt, sha256Hex } from './receipt-crypto.mjs';

const SENTINEL = '<!-- PREREG-SEAL-BELOW -->';
const REEF_PATH = 'data/pmu/reef/reef-144.json';
const LENS_PATH = 'data/pmu/snippet-library-144.json';
// The frozen held-out (Section 5 ground truth). Pinned the instant it exists;
// until then the seal records it as NOT-YET-FROZEN so the gap is explicit, never
// silently absent. The clock only "starts honest" once this hash is locked.
const GROUND_TRUTH_PATH = 'docs/research/pmu-shape-detection-ground-truth.json';

function fail(msg) { console.error(`✗ ${msg}`); process.exitCode = 1; }

function fileSha(path) {
  if (!existsSync(path)) return null;
  return sha256Hex(readFileSync(path, 'utf8'));
}

// Split a manifest into { body, hasSentinel }. The body is the frozen,
// hash-pinned region: everything up to and INCLUDING the sentinel line. If the
// manifest has no sentinel yet, the whole file is the body and we append one.
function splitBody(raw) {
  const idx = raw.indexOf(SENTINEL);
  if (idx === -1) return { body: raw.trimEnd() + '\n\n' + SENTINEL + '\n', hasSentinel: false };
  const end = idx + SENTINEL.length;
  return { body: raw.slice(0, end) + '\n', hasSentinel: true };
}

function renderSealBlock(seal, manifestRel) {
  return [
    '',
    '<!-- This block is auto-generated by scripts/pmu/prereg-seal.mjs. Do NOT hand-edit. -->',
    '<!-- It lives BELOW the sentinel and is therefore NOT part of the hashed frozen body. -->',
    '',
    '### Bearer seal — `pmu-prereg/v1`',
    '',
    '| Field | Value |',
    '|-------|-------|',
    `| sealed_at_note | ${seal.sealed_at_note} |`,
    `| manifest_body_sha256 | \`${seal.manifest_body_sha256}\` |`,
    `| reef_sha256 (\`${REEF_PATH}\`) | \`${seal.reef_sha256 ?? 'MISSING'}\` |`,
    `| lens_sha256 (\`${LENS_PATH}\`) | \`${seal.lens_sha256 ?? 'MISSING'}\` |`,
    `| ground_truth_sha256 (\`${GROUND_TRUTH_PATH}\`) | ${seal.ground_truth_sha256 ? '`' + seal.ground_truth_sha256 + '`' : '**NOT YET FROZEN** (held-out not generated)'} |`,
    `| pubkey_hex (host identity) | \`${seal.pubkey_hex}\` |`,
    `| sig_hex (ed25519) | \`${seal.sig_hex}\` |`,
    `| token sha256 | \`${seal.sha256}\` |`,
    '',
    '> Verify: `node scripts/pmu/prereg-seal.mjs ' + manifestRel + ' --verify`',
    '> A re-seal that changes the body hash means the hypothesis was edited after pre-registration — void.',
    '',
  ].join('\n');
}

function main() {
  const args = process.argv.slice(2);
  const manifestArg = args.find(a => !a.startsWith('--'));
  const doVerify = args.includes('--verify');
  const asJson = args.includes('--json');
  if (!manifestArg) { fail('usage: prereg-seal.mjs <manifest.md> [--verify] [--json]'); return; }

  const manifestPath = resolve(manifestArg);
  if (!existsSync(manifestPath)) { fail(`manifest not found: ${manifestPath}`); return; }
  const manifestRel = manifestArg;
  const sidecarPath = join(dirname(manifestPath), basename(manifestPath).replace(/\.md$/, '') + '.seal.json');

  const raw = readFileSync(manifestPath, 'utf8');
  const { body } = splitBody(raw);
  const bodySha = sha256Hex(body);
  const reefSha = fileSha(REEF_PATH);
  const lensSha = fileSha(LENS_PATH);
  const gtSha = fileSha(GROUND_TRUTH_PATH);

  if (doVerify) {
    if (!existsSync(sidecarPath)) { fail(`no seal sidecar at ${sidecarPath} — run without --verify to seal`); return; }
    const seal = JSON.parse(readFileSync(sidecarPath, 'utf8'));
    const v = verifyReceipt(seal);
    const bodyOk = seal.manifest_body_sha256 === bodySha;
    const reefOk = seal.reef_sha256 === reefSha;
    const lensOk = seal.lens_sha256 === lensSha;
    // ground truth: if the seal pinned a hash, it must still match; if the seal
    // pinned null (not yet frozen) we don't fault a still-absent held-out.
    const gtOk = seal.ground_truth_sha256 ? (seal.ground_truth_sha256 === gtSha) : (gtSha === null);
    // HARD GATES = the hypothesis body + the LENS the study senses against (snippet-library) + the
    // held-out. The lexicon reef (reef-144.json) is ADVISORY: it is a LIVING artifact the reef-self-loop
    // legitimately mutates, and the in-fence study senses against the LENS, not reef-144 — so a reef
    // drift is reported but does NOT break the seal (a hard gate on a self-evolving file would cry wolf).
    const allOk = v.ok && bodyOk && lensOk && gtOk;
    const report = {
      ok: allOk, signature: v.ok ? 'valid' : `INVALID (${v.reason})`,
      body: bodyOk ? 'unchanged' : `CHANGED (manifest edited since seal: ${bodySha} != ${seal.manifest_body_sha256})`,
      reef: reefOk ? 'unchanged' : `ADVISORY: lexicon reef evolved since seal (self-loop) — not a study input; lens is the gate`,
      lens: lensOk ? 'unchanged' : `CHANGED (${lensSha} != ${seal.lens_sha256})`,
      ground_truth: seal.ground_truth_sha256
        ? (gtOk ? 'unchanged' : `CHANGED (held-out altered since seal: ${gtSha} != ${seal.ground_truth_sha256})`)
        : (gtSha === null ? 'not-yet-frozen (consistent with seal)' : 'APPEARED (held-out created after seal — reseal to pin it)'),
    };
    if (asJson) { console.log(JSON.stringify(report, null, 2)); }
    else {
      console.log(`${allOk ? '✓ SEAL INTACT' : '✗ SEAL BROKEN'}`);
      console.log(`  signature   : ${report.signature}`);
      console.log(`  body        : ${report.body}`);
      console.log(`  reef        : ${report.reef}`);
      console.log(`  lens        : ${report.lens}`);
      console.log(`  ground_truth: ${report.ground_truth}`);
    }
    if (!allOk) process.exitCode = 1;
    return;
  }

  // Seal: build the token, sign it, write sidecar, inject the rendered block.
  const token = sealReceipt({
    kind: 'pmu-prereg/v1',
    sealed_at_note: 'frozen before held-out opened (no machine clock in scripts — pin via git commit time)',
    manifest: manifestRel,
    manifest_body_sha256: bodySha,
    reef_path: REEF_PATH, reef_sha256: reefSha,
    lens_path: LENS_PATH, lens_sha256: lensSha,
    ground_truth_path: GROUND_TRUTH_PATH, ground_truth_sha256: gtSha,
  });

  writeFileSync(sidecarPath, JSON.stringify(token, null, 2) + '\n');

  const { body: frozen } = splitBody(raw);
  const rebuilt = frozen + renderSealBlock(token, manifestRel);
  writeFileSync(manifestPath, rebuilt);

  if (asJson) {
    console.log(JSON.stringify({ ok: true, sidecar: sidecarPath, manifest_body_sha256: bodySha, reef_sha256: reefSha, lens_sha256: lensSha, pubkey_hex: token.pubkey_hex }, null, 2));
  } else {
    console.log('✓ SEALED — bearer hypothesis token written');
    console.log(`  sidecar            : ${sidecarPath}`);
    console.log(`  manifest_body_sha256: ${bodySha}`);
    console.log(`  reef_sha256         : ${reefSha ?? 'MISSING'}`);
    console.log(`  lens_sha256         : ${lensSha ?? 'MISSING'}`);
    console.log(`  ground_truth_sha256 : ${gtSha ?? 'NOT YET FROZEN (held-out not generated)'}`);
    console.log(`  signed by           : ${token.pubkey_hex.slice(0, 16)}…`);
    console.log('  Commit now — the git commit time is the trusted "sealed before" timestamp.');
  }
}

main();
