// GENERATED by scripts/vna/door-labels.mjs — never edit by hand (C243). One name for the keys door: the pill (steer-ui.mjs)
// and this page (vna-engines.ts) both read it; the guard diffs this file against the generator's --print.
export const ENGINE_KEYS_LABEL = "⚙️🔑 Engine & Keys";
export const ENGINE_KEYS_LABEL_HTML = "⚙️🔑 Engine &amp; Keys";
export const ENGINE_KEYS_COMMAND = "vna.openEnginesConfig";
